name: integration test
on: 
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
jobs:
  widget_test: 
    name: flutter widget test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - 
        name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt update
          sudo apt-get install google-chrome-stable
          sudo wget https://sites.google.com/chromium.org/driver/downloads#:~:text=%2C%20please%20download-,ChromeDriver%20105.0.5195.52,-If%20you%20are
          sudo unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.4"
      - name: flutter pub get
        run: flutter pub get
      - name: run Chrome
        run: chromedriver --port=4444
      - name: flutter widget test
        run:  flutter drive --driver=test_driver/integration_test.dart --target=integration_test/integration_test.dart -d web-server --no-headless